spring.application.name=appointment

spring.datasource.url=jdbc:mysql://localhost:3306/salon_db
spring.datasource.username=salon_user
spring.datasource.password=salon123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=3f8a2b1c9d4e7f6a5b0c3d2e1f8a9b4c7d6e5f0a1b2c3d4e5f6a7b8c9d0e1f2a
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000

server.port=8080
